server:
  port: 8081

spring:
  application:
    name: item-service
  datasource:
    url: jdbc:mysql:///leyou?useUnicode=true&characterEncoding=utf8
    username: root
    password: lixin713713
  rabbitmq:
    host: 192.168.230.129
    username: leyou
    password: leyou
    virtual-host: /leyou
    template:
      exchange: LEYOU.ITEM.EXCHANGE

eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
  instance:
    lease-expiration-duration-in-seconds: 30
    lease-renewal-interval-in-seconds: 5

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

