server:
  port: 8088
spring:
  application:
    name: cart-service
  redis:
    host: 192.168.230.129
    password: 713713
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
    registry-fetch-interval-seconds: 10
  instance:
    lease-renewal-interval-in-seconds: 5 # 每隔5秒发送一次心跳
    lease-expiration-duration-in-seconds: 10 # 10秒不发送就过期
leyou:
  jwt:
    pubKeyPath: D:\\IdeaProjects\\tmp\\rsa\\rsa.pub # 公钥地址
    cookieName: LY_TOKEN # cookie的名称